export const SUPPORTED_LANGS = ["en", "de", "es", "fr", "it", "pt", "zh"] as const;

export type SupportedLang = (typeof SUPPORTED_LANGS)[number];

export const UI_TEXT: Record<SupportedLang, Record<string, string>> = {
  en: {
    work: "Work",
    notes: "Notes",
    contact: "Contact",
    selectedWork: "Selected work",
    selectedProjects: "Selected Projects",
    personalTools: "Personal tools",
    capabilities: "Capabilities",
    technicalExpertise: "Technical expertise",
    writing: "Writing",
    publications: "Publications",
    available: "Available for selected engagements.",
    based: "Based in Brazil, working across Zürich and São Paulo.",
    stack: "Stack",
    metrics: "Metrics",
    back: "Back",
    allRightsReserved: "All rights reserved.",
  },
  pt: {
    work: "Trabalho",
    notes: "Notas",
    contact: "Contato",
    selectedWork: "Trabalhos selecionados",
    selectedProjects: "Projetos selecionados",
    personalTools: "Ferramentas pessoais",
    capabilities: "Capacidades",
    technicalExpertise: "Especialidade técnica",
    writing: "Escrita",
    publications: "Publicações",
    available: "Disponível para projetos selecionados.",
    based: "Baseado no Brasil, atuando entre Zürich e São Paulo.",
    stack: "Stack",
    metrics: "Métricas",
    back: "Voltar",
    allRightsReserved: "Todos os direitos reservados.",
  },
  de: {
    work: "Arbeit",
    notes: "Notizen",
    contact: "Kontakt",
    selectedWork: "Ausgewählte Arbeit",
    selectedProjects: "Ausgewählte Projekte",
    personalTools: "Persönliche Werkzeuge",
    capabilities: "Fähigkeiten",
    technicalExpertise: "Technische Expertise",
    writing: "Texte",
    publications: "Publikationen",
    available: "Verfügbar für ausgewählte Projekte.",
    based: "In Brasilien ansässig, tätig zwischen Zürich und São Paulo.",
    stack: "Stack",
    metrics: "Metriken",
    back: "Zurück",
    allRightsReserved: "Alle Rechte vorbehalten.",
  },
  es: {
    work: "Trabajo",
    notes: "Notas",
    contact: "Contacto",
    selectedWork: "Trabajo seleccionado",
    selectedProjects: "Proyectos destacados",
    personalTools: "Herramientas personales",
    capabilities: "Capacidades",
    technicalExpertise: "Experiencia técnica",
    writing: "Escritura",
    publications: "Publicaciones",
    available: "Disponible para proyectos seleccionados.",
    based: "Basado en Brasil, trabajando entre Zúrich y São Paulo.",
    stack: "Stack",
    metrics: "Métricas",
    back: "Volver",
    allRightsReserved: "Todos los derechos reservados.",
  },
  fr: {
    work: "Travail",
    notes: "Notes",
    contact: "Contact",
    selectedWork: "Travaux sélectionnés",
    selectedProjects: "Projets sélectionnés",
    personalTools: "Outils personnels",
    capabilities: "Compétences",
    technicalExpertise: "Expertise technique",
    writing: "Écriture",
    publications: "Publications",
    available: "Disponible pour des missions sélectionnées.",
    based: "Basé au Brésil, travaillant entre Zurich et São Paulo.",
    stack: "Stack",
    metrics: "Métriques",
    back: "Retour",
    allRightsReserved: "Tous droits réservés.",
  },
  it: {
    work: "Lavoro",
    notes: "Note",
    contact: "Contatto",
    selectedWork: "Lavori selezionati",
    selectedProjects: "Progetti selezionati",
    personalTools: "Strumenti personali",
    capabilities: "Competenze",
    technicalExpertise: "Competenza tecnica",
    writing: "Scrittura",
    publications: "Pubblicazioni",
    available: "Disponibile per incarichi selezionati.",
    based: "Con base in Brasile, lavora tra Zurigo e São Paulo.",
    stack: "Stack",
    metrics: "Metriche",
    back: "Indietro",
    allRightsReserved: "Tutti i diritti riservati.",
  },
  zh: {
    work: "工作",
    notes: "笔记",
    contact: "联系",
    selectedWork: "精选工作",
    selectedProjects: "精选项目",
    personalTools: "个人工具",
    capabilities: "能力",
    technicalExpertise: "技术专长",
    writing: "写作",
    publications: "出版物",
    available: "可接受精选合作。",
    based: "常驻巴西，工作覆盖苏黎世和圣保罗。",
    stack: "技术栈",
    metrics: "指标",
    back: "返回",
    allRightsReserved: "保留所有权利。",
  },
};

export function normalizeLang(lang: string): SupportedLang {
  return SUPPORTED_LANGS.includes(lang as SupportedLang) ? (lang as SupportedLang) : "en";
}

export function getUiText(lang: string) {
  return UI_TEXT[normalizeLang(lang)];
}
